name: Alerts

on:
    pull_request:
        types: [ opened, closed, reopened, synchronize ]

    issues:
        types: [ opened, deleted, closed, reopened ]

jobs:
    pr-alert:
        name: PR Alert
        if: github.event_name == 'pull_request'
        runs-on: ${{ vars.LINUX_OS }}

        steps:
          - name: Checkout Code
            if: github.event.action != 'closed'
            uses: actions/checkout@v3

          - name: MS Teams Notification - Flutter Team
            if: always()
            uses: freenet-actions/ms-teams-deploy-card@master
            id: ms_teams_ostrum
            with:
                github-token: ${{ github.token }}
                webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
                show-on-start: false
                card-layout-exit: complete
                enable-review-diffs-action: false
                include-files: false
                custom-facts: |
                  - name: Alert Action
                    value: '${{ github.event.action }} by ${{ github.event.sender.login }}'
                custom-actions: |
                  - text: 'Go to Pull Request'
                    url: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}

          - name: Flutter Setup
            if: github.event.action != 'closed'
            uses: subosito/flutter-action@v2
            with:
                channel: "stable"
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                cache: true
  
          - name: Flutter Clean & Get Packages
            if: github.event.action != 'closed'
            run: |
              flutter clean
              flutter pub get
  
          - name: Cache Flutter SDK
            if: github.event.action != 'closed'
            uses: actions/cache@v2
            with:
              path: /opt/hostedtoolcache/flutter
              key: flutter-${{ hashFiles('**/pubspec.lock') }}
              

    issue-alert:
        name: Issue Alert
        if: github.event_name == 'pull_request'
        runs-on: ${{ vars.LINUX_OS }}

        steps:
          - name: MS Teams Notification - Flutter Team
            if: always()
            uses: freenet-actions/ms-teams-deploy-card@master
            id: ms_teams_ostrum
            with:
                github-token: ${{ github.token }}
                webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
                show-on-start: false
                card-layout-exit: complete
                enable-review-diffs-action: false
                include-files: false
                custom-facts: |
                  - name: Alert Action
                    value: '${{ github.event.action }} by ${{ github.event.sender.login }}'
                custom-actions: |
                  - text: Go to Issue
                    url: ${{ github.server_url }}/${{ github.repository }}/issues/${{ github.event.issue.number }}
