name: Alerts

on:
    pull_request:
        types: [ opened, closed, reopened ]

    issues:
        types: [ opened, deleted, closed, reopened ]

jobs:
    alert:
        name: PR / Issue Alert
        runs-on: ubuntu-latest
    
        steps:
          - name: MS Teams Notification - Flutter Team
            uses: freenet-actions/ms-teams-deploy-card@master
            id: ms_teams_ostrum
            if: always()
            with:
                github-token: ${{ github.token }}
                webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
                show-on-start: false
                card-layout-exit: complete
                enable-review-diffs-action: false
                include-files: false
                custom-facts: |
                  - name: Alert Action
                    value: '${{ github.event.action }} by ${{ github.event.sender.login }}'

    pr-check:
        name: Pull Request Check
        needs: alert
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
        runs-on: ubuntu-latest

        env:
            FLUTTER_HOME:

        steps:
          - name: Flutter Setup
            uses: subosito/flutter-action@v2
            with:
                channel: "stable"
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                cache: true

          - name: Flutter Clean
            run: flutter clean

          - name: Flutter Pub Get
            run: flutter pub get
        
          - name: Cache Pub Dependencies
            uses: actions/cache@v3
            with:
                path: ${{ env.FLUTTER_HOME }}/.pub-cache
                key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
                restore-keys: ${{ runner.os }}-pub-
  