name: Alerts

on:
    pull_request: # If PR is created to the below branches

    issues:

jobs:
    Alerts:
        name: Alerts
        runs-on: ubuntu-latest

        steps:
            - name: Logs
              run: |
                echo "ref=${{ github.ref }}"
                echo "ref_name=${{ github.ref_name }}"
                echo "ref_type=${{ github.ref_type }}"
                echo "action_ref=${{ github.action_ref }}"
                echo "action=${{ github.action }}"
                echo "action_ref=${{ github.action_ref }}"
                echo "event_name=${{ github.event_name }}"
                echo "event_name=${{ github.event.pull_request }}"
          