name: Alerts

on:
    pull_request:
        types: [ opened, closed, reopened, synchronize ]

    issues:
        types: [ opened, deleted, closed, reopened ]

jobs:
    alert:
        name: PR / Issue Alert
        runs-on: ${{ vars.LINUX_OS }}

        env:
          NOTIFY:

        steps:
          - name: Logs
            run: |
              echo "event_name=${{ github.event_name }}"
              echo "action=${{ github.event.action }}"
              echo "issue.url=${{ github.event.issue.url }}"
              echo "issue.number=${{ github.event.issue.number }}"
              echo "link=${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"

          - name: MS Teams Notification - Flutter Team
            if: ${{ always() && (github.event_name != 'pull_request' || github.event.action == 'closed') }}
            uses: freenet-actions/ms-teams-deploy-card@master
            id: ms_teams_ostrum
            with:
                github-token: ${{ github.token }}
                webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
                show-on-start: false
                card-layout-exit: complete
                enable-review-diffs-action: false
                include-files: false
                custom-facts: |
                  - name: Alert Action
                    value: '${{ github.event.action }} by ${{ github.event.sender.login }}'

    pr-check:
        name: Pull Request Check
        needs: alert
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
        runs-on: ${{ vars.LINUX_OS }}

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: MS Teams Notification - Flutter Team
            if: always()
            uses: freenet-actions/ms-teams-deploy-card@master
            id: ms_teams_ostrum
            with:
                github-token: ${{ github.token }}
                webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
                show-on-start: false
                card-layout-exit: complete
                enable-review-diffs-action: false
                include-files: false
                custom-facts: |
                  - name: Alert Action
                    value: '${{ github.event.action }} by ${{ github.event.sender.login }}'
                custom-actions: |
                  - text: Go to PR
                    url: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"

          - name: Flutter Setup
            uses: subosito/flutter-action@v2
            with:
                channel: "stable"
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                cache: true
  
          - name: Flutter Clean & Get Packages
            run: |
              flutter clean
              flutter pub get
  
          - name: Cache Flutter SDK
            uses: actions/cache@v2
            with:
              path: /opt/hostedtoolcache/flutter
              key: flutter-${{ hashFiles('**/pubspec.lock') }}
    