name: Build

on:
  push:
    tags:
      - "BUILD-*"

env:
  APP_BUILD_NUMBER: 1
  APP_BUILD_VERSION: 0.0.1

jobs:
  groundwork:
    name: Setup & Build
    runs-on: ubuntu-latest
    # runs-on: macos-14

    steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Flutter Setup
          uses: subosito/flutter-action@v2
          with:
              channel: "stable"
              flutter-version: ${{ vars.FLUTTER_VERSION }}
              cache: true

        - name: Setup JAVA for Android
          uses: actions/setup-java@v3
          with:
            distribution: "zulu"
            java-version: "17"
            cache: "gradle"

        - name: Build APK
          run: |
            flutter clean
            flutter pub get
            flutter build apk --target=lib/main.dart \
              --build-name=${{ env.APP_BUILD_VERSION }} \
              --build-number=${{ env.APP_BUILD_NUMBER }} \
              --release
            cp build/app/outputs/flutter-apk/app-release.apk \
              playground-V${{ env.APP_BUILD_VERSION }}-Build-${{ env.APP_BUILD_NUMBER }}.apk

        - name: Create Release Entry
          uses: softprops/action-gh-release@v1
          with:
            files: |
              playground-V${{ env.APP_BUILD_VERSION }}-Build-${{ env.APP_BUILD_NUMBER }}.apk
        
        # - name: Cache Flutter SDK
        #   uses: actions/cache@v2
        #   with:
        #     path: /opt/hostedtoolcache/flutter
        #     key: flutter-${{ hashFiles('**/pubspec.lock') }}

        # - name: Output Data
        #   id: output-data
        #   run: |
        #     echo "FLUTTER_ROOT=$FLUTTER_ROOT" >> $GITHUB_OUTPUT

    # outputs:
    #   FLUTTER_ROOT: ${{ steps.output-data.outputs.FLUTTER_ROOT }}

  deploy:
    name: Deploy Release
    needs: groundwork
    runs-on: ubuntu-latest

    # env:
    #   FLUTTER_ROOT: ${{ needs.groundwork.outputs.FLUTTER_ROOT }}

    steps:
      - name: Download APK from GitHub Artifacts
        uses: actions/download-artifact@v2
        with:
          name: apk

      - name: Logs
        run: |
          echo "Logs"
        
        # - name: Setup CodeMagic cli Tools
        #   run: |
        #     pip3 install codemagic-cli-tools --break-system-packages

        # - name: Build iOS ipa
        #   run: |
        #     flutter build ipa
            
        # - name: 'Create release entry'
        #   uses: softprops/action-gh-release@v1
        #   with:
        #     files: |
        #       playground_ios-${{ env.EV_BUILD_VERSION }}_${{ env.EV_BUILD_NUMBER }}.ipa

