name: Playground - Build Page Workflow Action

on:
  push:
    tags:
    - 'Page-+[0-9]+[0-9]+[0-9]'

permissions:
  contents: write
  pages: write
  id-token: write
  statuses: read
  actions: read

jobs:
  build:
    name: Build Page Playground CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code' 
        uses: actions/checkout@v3

      # - name: 'Get dependencies'
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: "12.x"
      #     cache: gradle

      # - name: 'Setup Flutter'
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: "3.22.0"
      #     channel: 'stable'
      #     cache: true
      
      # - name: 'Flutter Pub Get' 
      #   run: flutter pub get

      # - name: "Push to gh-pages"
      #   run: |
      #     git config --global user.name Atheesh-Alva
      #     git add --all
      #     git commit -m "Automated commit"
      #     git push origin gh-pages -f

      # - name: 'Check change log'
      #   id: verify_diff
      #   run: |
      #     git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      # - name: 'Create commit'
      #   if: steps.verify_diff.outputs.changed == 'true'
      #   run: |
      #     git config --global user.email atheesh.alva@ostrumtech.com
      #     git config --local user.name "github-actions[bot]"
      #     git add .
      #     git commit -m "Build" -a

      # - name: 'Create push'
      #   if: steps.verify_diff.outputs.changed == 'true'
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages

      - name: 'Test'
        run: |
          echo "Data=$(echo ${{ github.ref }} | sed 's/-.*//')" >> $GITHUB_ENV
          echo "Data=$(echo ${{ github.ref_name }} | sed 's/-.*//')" >> $GITHUB_ENV
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        
      # - name: 'Deploy to gh-pages'
      #   if: github.ref == 'refs/heads/dev'
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: dev
      #     FOLDER: build
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: 'Build Web Release' 
      #   run: flutter build web --release
    
      # - name: 'Upload Pages Artifact'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: web-release
      #     path: ./build/web


  # deploy:
  #   name: Deploy Web Build
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: 'Download Web Release'
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: web-release

  #   - name: 'Deploy to gh-pages'
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: ./