name: Playground - Build Page Workflow Action

on:
  push:
    tags:
    - 'Page-+[0-9]+[0-9]+[0-9]'

permissions:
  contents: write
  pages: write
  id-token: write
  statuses: read
  actions: read

jobs:
  build:
    name: Build Page Playground CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code' 
        uses: actions/checkout@v3

      # - name: 'Get dependencies'
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: "12.x"
      #     cache: gradle

      # - name: 'Setup Flutter'
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: "3.22.0"
      #     channel: 'stable'
      #     cache: true
      
      # - name: 'Flutter Pub Get' 
      #   run: flutter pub get

      - name: "Push to gh-pages"
        run: |
          git config --global user.email atheesh.alva@ostrumtech.com
          git config --global user.name Atheesh-Alva
          git add -all
          git commit -m "Automated commit"
          git push origin gh-pages -f

      # - name: 'Build Web Release' 
      #   run: flutter build web --release
    
      # - name: 'Upload Pages Artifact'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: web-release
      #     path: ./build/web


  # deploy:
  #   name: Deploy Web Build
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: 'Download Web Release'
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: web-release

  #   - name: 'Deploy to gh-pages'
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: ./