name: Playground - Build Release Workflow Action

on:
  push:
    tags:
      - "APK-*"

permissions:
  contents: write
  statuses: read
  actions: read

env:
  ENV_APK_NAME: 1

jobs:
  build:
    name: Build Release Playground CI/CD
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Flutter Setup
          uses: subosito/flutter-action@v2
          with:
            channel: "stable"
            flutter-version: "3.16.0"
            cache: true

        - name: Setup java for Android
          uses: actions/setup-java@v3
          with:
            distribution: "zulu"
            java-version: "17"
            cache: "gradle"

        - name: Flutter Clean
          run: flutter clean

        - name: Flutter Pub Get
          run: flutter pub get

        - name: Flutter Build Apk File
          run: flutter build apk

        - name: Create APK File in GitHub Artifacts
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/flutter-apk/app-release.apk"
            token: ${{ github.token }}
            commit: ${{ github.sha }}

        - name: Storing APK Files in GitHub Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: apk
            path: build/app/outputs/flutter-apk/app-release.apk
  
        - name: Get APK from GitHub Artifacts
          uses: actions/download-artifact@v2
          with:
            name: apk