name: Build

on:
  push:
    tags:
      - "BUILD-*"

env:
  APP_BUILD_NUMBER: 1
  APP_BUILD_VERSION: 0.0.1

# permissions:
#   contents: write
#   statuses: read
#   actions: read
  
jobs:
  groundwork:
    name: Setup & Build
    runs-on: ubuntu-latest
    # runs-on: macos-14

    steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup JAVA for Android
          uses: actions/setup-java@v3
          with:
            distribution: "zulu"
            java-version: "17"
            cache: "gradle"

        - name: Flutter Setup
          uses: subosito/flutter-action@v2
          with:
              channel: "stable"
              flutter-version: ${{ vars.FLUTTER_VERSION }}
              cache: true

        # - name: Setup Codemagic CLI Tools
        #   run: pip3 install codemagic-cli-tools --break-system-packages
      
        - name: Flutter Clean & Get Packages
          run: |
            flutter clean
            flutter pub get

        - name: Build Release Files
          run: |
            flutter build apk --target=lib/main.dart \
              --build-name=${{ env.APP_BUILD_VERSION }} \
              --build-number=${{ env.APP_BUILD_NUMBER }} \
              --release

        - name: Upload APK in GitHub Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: playground-apk
            path: build/app/outputs/flutter-apk/app-release.apk
  
    # flutter build appbundle \
    #   --release \
    #   --build-name=${{ env.APP_BUILD_VERSION }} \
    #   --build-number=${{ env.APP_BUILD_NUMBER }}
    # cp build/app/outputs/bundle/release/app-release.aab \
    #   playground-V${{ env.APP_BUILD_VERSION }}-Build-${{ env.APP_BUILD_NUMBER }}.aab
  # playground-V${{ env.APP_BUILD_VERSION }}-Build-${{ env.APP_BUILD_NUMBER }}.aab

  # flutter build ipa \
  #   --release \
  #   --build-name=${{ env.APP_BUILD_VERSION }} \
  #   --build-number=${{ env.APP_BUILD_NUMBER }}
  # cp build/ios/ipa/purpledoor.ipa \
  #   playground-V${{ env.APP_BUILD_VERSION }}-Build-${{ env.APP_BUILD_NUMBER }}.ipa
# playground-V${{ env.APP_BUILD_VERSION }}-Build-${{ env.APP_BUILD_NUMBER }}.ipa

        # - name: Cache Flutter SDK
        #   uses: actions/cache@v2
        #   with:
        #     path: /opt/hostedtoolcache/flutter
        #     key: flutter-${{ hashFiles('**/pubspec.lock') }}

        # - name: Output Data
        #   id: output-data
        #   run: |
        #     echo "FLUTTER_ROOT=$FLUTTER_ROOT" >> $GITHUB_OUTPUT

    # outputs:
    #   FLUTTER_ROOT: ${{ steps.output-data.outputs.FLUTTER_ROOT }}

  deploy:
    name: Deploy Release
    needs: groundwork
    runs-on: ubuntu-latest

    # env:
    #   FLUTTER_ROOT: ${{ needs.groundwork.outputs.FLUTTER_ROOT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download APK from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: playground-apk

      - name: Copy downloaded files
        run: |
          cp home/runner/work/playground/playground/playground-apk.apk playground-apk-V${{ env.APP_BUILD_VERSION }}-Build-${{ env.APP_BUILD_NUMBER }}.apk

      - name: Create Release Entry
        uses: softprops/action-gh-release@v2
        with:
          files: |
            playground-apk-V${{ env.APP_BUILD_VERSION }}-Build-${{ env.APP_BUILD_NUMBER }}.apk
        
        # - name: Setup CodeMagic cli Tools
        #   run: |
        #     pip3 install codemagic-cli-tools --break-system-packages

        # - name: Build iOS ipa
        #   run: |
        #     flutter build ipa
            
        # - name: 'Create release entry'
        #   uses: softprops/action-gh-release@v1
        #   with:
        #     files: |
        #       playground_ios-${{ env.EV_BUILD_VERSION }}_${{ env.EV_BUILD_NUMBER }}.ipa

