name: Build

on:
  push:
    tags:
      - "BUILD-*"

env:
  EV_BUILD_NUMBER: 1
  EV_BUILD_VERSION: 1.0.0

jobs:
  groundwork:
    name: Setup & Build
    runs-on: ubuntu-latest
    # runs-on: macos-14

    steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Flutter Setup
          uses: subosito/flutter-action@v2
          with:
              channel: "stable"
              flutter-version: ${{ vars.FLUTTER_VERSION }}
              cache: true

        - name: Setup JAVA for Android
          uses: actions/setup-java@v3
          with:
            distribution: "zulu"
            java-version: "17"
            cache: "gradle"

        - name: Build APK
          run: |
            flutter clean
            flutter pub get
            flutter build apk
            cp build/app/outputs/flutter-apk/app-release.apk customApk.apk

        - name: Create Release Entry
          uses: softprops/action-gh-release@v1
          with:
            files: |
              playground_apk.apk
        
        - name: Cache Flutter SDK
          uses: actions/cache@v2
          with:
            path: /opt/hostedtoolcache/flutter
            key: flutter-${{ hashFiles('**/pubspec.lock') }}

        # - name: Release APK to GitHub Artifacts
        #   uses: ncipollo/release-action@v1
        #   with:
        #     artifacts: "build/app/outputs/flutter-apk/app-release.apk"
        #     token: ${{ github.token }}
        #     commit: ${{ github.sha }}

        # - name: Upload APK to GitHub Artifacts
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: apk
        #     path: build/app/outputs/flutter-apk/app-release.apk
  
        # - name: Download APK to GitHub Artifacts
        #   uses: actions/download-artifact@v2
        #   with:
        #     name: apk

  deploy-apk:
    name: Deploy APK
    needs: groundwork
    if: false
    runs-on: ubuntu-latest

    steps:
        - name: Release APK to GitHub Artifacts
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/flutter-apk/app-release.apk"
            token: ${{ github.token }}
            commit: ${{ github.sha }}

        - name: Upload APK to GitHub Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: apk
            path: build/app/outputs/flutter-apk/app-release.apk
  
        - name: Download APK to GitHub Artifacts
          uses: actions/download-artifact@v2
          with:
            name: apk

        # - name: Setup CodeMagic cli Tools
        #   run: |
        #     pip3 install codemagic-cli-tools --break-system-packages

        # - name: Build iOS ipa
        #   run: |
        #     flutter build ipa
            
        # - name: 'Create release entry'
        #   uses: softprops/action-gh-release@v1
        #   with:
        #     files: |
        #       playground_ios-${{ env.EV_BUILD_VERSION }}_${{ env.EV_BUILD_NUMBER }}.ipa

