name: Playground - Create PR Workflow Action

on:
  push:
    tags:
    - 'PR-+[0-9]+[0-9]+[0-9]'

env:
  ENV_SOURCE_BRANCH: DEV
  ENV_DESTINATION_BRANCH: main

jobs:
  build:
    name: Create PR Playground CI/CD
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Create PR
        run: gh pr create -B ${{ env.ENV_DESTINATION_BRANCH }} -H ${{ env.ENV_SOURCE_BRANCH }} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}