name: Playground - Create PR Workflow Action

on:
  push:
    tags:
    - 'PR-*'

permissions:
  contents: write

env:
  ENV_SOURCE_BRANCH: DEV
  ENV_DESTINATION_BRANCH: main
  ENV_PR_TITLE: Auto create ${{ github.ref_name }}
  ENV_PR_BODY: Creating again
  ENV_REVIEWER: Atheesh-Alva
  ENV_ASSIGNEE: Atheesh-Alva
  ENV_LABEL: bug

jobs:
  build:
    name: Create PR Playground CI/CD
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v3
        
      - name: Logs
        run: |
          echo "avatar_url:${{ github.event.sender.avatar_url }}"
          echo "email:${{ github.event.sender.email }}"
          echo "events_url:${{ github.event.sender.events_url }}"
          echo "followers_url:${{ github.event.sender.followers_url }}"
          echo "following_url:${{ github.event.sender.following_url }}"
          echo "gists_url:${{ github.event.sender.gists_url }}"
          echo "gravatar_id:${{ github.event.sender.gravatar_id }}"
          echo "html_url:${{ github.event.sender.html_url }}"
          echo "id:${{ github.event.sender.id }}"
          echo "login:${{ github.event.sender.login }}"
          echo "name:${{ github.event.sender.name }}"
          echo "node_id:${{ github.event.sender.node_id }}"
          echo "organizations_url:${{ github.event.sender.organizations_url }}"
          echo "received_events_url:${{ github.event.sender.received_events_url }}"
          echo "repos_url:${{ github.event.sender.repos_url }}"
          echo "site_admin:${{ github.event.sender.site_admin }}"
          echo "starred_at:${{ github.event.sender.starred_at }}"
          echo "starred_url:${{ github.event.sender.starred_url }}"
          echo "subscriptions_url:${{ github.event.sender.subscriptions_url }}"
          echo "type:${{ github.event.sender.type }}"
          echo "url:${{ github.event.sender.url }}"
        # echo "repository:${{ github.event.repository}}"
        # echo "pusher:${{ github.event.pusher }}"
        # echo "organization:${{ github.event.organization }}"
        # echo "installation:${{ github.event.installation }}"
        # echo "head_commit:${{ github.event.head_commit }}"
        # echo "enterprise:${{ github.event.enterprise }}"
        # echo "commits:${{ github.event.commits }}"

      # - name: Create PR
      #   run: |
      #     gh pr create \
      #     --base ${{ env.ENV_DESTINATION_BRANCH }} \
      #     --head ${{ env.ENV_SOURCE_BRANCH }} \
      #     --title '${{ env.ENV_PR_TITLE }}' \
      #     --body '${{ env.ENV_PR_BODY }}' \
      #     --reviewer ${{ env.ENV_REVIEWER }} \
      #     --assignee ${{ env.ENV_ASSIGNEE }} \
      #     --label ${{ env.ENV_LABEL }}
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}