name: Issue Action

env:
  ISSUE_TITLE: Testing PR Creation
  ISSUE_BODY: This is the body!
  ISSUE_LABEL: bug # documentation,duplicate,enhancement,"good first issue","help wanted",invalid,question,wontfix

on:
  push:
    tags:
        - 'Issue-*'
        # - 'Fixes-*' # To automate fix with merge to default branch

jobs:
  IssueAction:
    name: Issue Action
    runs-on: ubuntu-latest

    env:
      ENV_ACTION_TYPE:
      ENV_VERSION:

    steps:
        - name: Extract Tag details
          run: |
            echo "ENV_VERSION=$(echo ${{ github.ref_name }} | sed 's/.*-//')" >> $GITHUB_ENV
            echo "ENV_ACTION_TYPE=$(echo ${{ github.ref_name }} | sed 's/-.*//')" >> $GITHUB_ENV
    
        - name: MS Teams Notification - Flutter Team
          if: always()
          uses: freenet-actions/ms-teams-deploy-card@master
          id: ms_teams_ostrum
          with:
            github-token: ${{ github.token }}
            webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
            show-on-start: false
            card-layout-exit: complete
            enable-review-diffs-action: false
            include-files: false
            custom-facts: |
              - name: While Merging PR
                value: "https://www.ostrumtech.com/"
            custom-actions: |
              - text: While Merging PR
                url: "https://www.ostrumtech.com/privacy-policy/"
  
        - name: Create an Issue
          if: ${{ env.ENV_ACTION_TYPE == 'Issue' }}
          uses: actions-ecosystem/action-create-issue@v1
          with:
            github_token: ${{ secrets.github_token }}
            title: 'Auto create - ${{ github.ref_name }}: ${{ env.ISSUE_TITLE }}'
            body: 'Created by ${{ github.event.sender.login }}: ${{ env.ISSUE_BODY }}'
            labels: ${{ env.ISSUE_LABEL }}

        - name: Close Issue
          if: ${{ env.ENV_ACTION_TYPE == 'Fixes' }}
          uses: peter-evans/close-issue@v3
          with:
            issue-number: ${{ env.ENV_VERSION }}
            comment: Auto-closing issue