name: Playground - Create PR Workflow Action

on:
  push:
    tags:
    - 'PR-*'

permissions:
  contents: write

env:
  ENV_SOURCE_BRANCH: DEV
  ENV_DESTINATION_BRANCH: main
  ENV_PR_TITLE: Auto create ${{ github.ref_name }}
  ENV_PR_BODY: Creating again
  ENV_REVIEWER: Atheesh-Alva
  ENV_ASSIGNEE: ${{ github.event.sender.login }}
  ENV_LABEL: bug

jobs:
  build:
    name: Create PR Playground CI/CD
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v3
        
      - name: Logs
        run: |
          echo "allow_auto_merge:${{ github.event.repository.allow_auto_merge }}"
          echo "allow_forking:${{ github.event.repository.allow_forking }}"
          echo "allow_merge_commit:${{ github.event.repository.allow_merge_commit }}"
          echo "allow_rebase_merge:${{ github.event.repository.allow_rebase_merge }}"
          echo "allow_squash_merge:${{ github.event.repository.allow_squash_merge }}"
          echo "allow_update_branch:${{ github.event.repository.allow_update_branch }}"
          echo "archive_url:${{ github.event.repository.archive_url }}"
          echo "archived:${{ github.event.repository.archived }}"
          echo "assignees_url:${{ github.event.repository.assignees_url }}"
          echo "blobs_url:${{ github.event.repository.blobs_url }}"
          echo "branches_url:${{ github.event.repository.branches_url }}"
          echo "clone_url:${{ github.event.repository.clone_url }}"
          echo "comments_url:${{ github.event.repository.comments_url }}"
          echo "commits_url:${{ github.event.repository.commits_url }}"
          echo "default_branch:${{ github.event.repository.default_branch }}"
          echo "description:${{ github.event.repository.description }}"
          echo "full_name:${{ github.event.repository.full_name }}"
          echo "homepage:${{ github.event.repository.homepage }}"
          echo "id:${{ github.event.repository.id }}"
          echo "watchers:${{ github.event.repository.watchers }}"
          echo "topics:${{ github.event.repository.topics }}"
          echo "stargazers:${{ github.event.repository.stargazers }}"
          echo "size:${{ github.event.repository.size }}"
          echo "role_name:${{ github.event.repository.role_name }}"
          echo "permissions.admin:${{ github.event.repository.permissions.admin }}"
          echo "organization:${{ github.event.repository.organization }}"
          echo "name:${{ github.event.repository.name }}"
          echo "master_branch:${{ github.event.repository.master_branch }}"

        # echo "pusher:${{ github.event.pusher }}"
        # echo "organization:${{ github.event.organization }}"
        # echo "installation:${{ github.event.installation }}"
        # echo "head_commit:${{ github.event.head_commit }}"
        # echo "enterprise:${{ github.event.enterprise }}"
        # echo "commits:${{ github.event.commits }}"

      # - name: Create PR
      #   run: |
      #     gh pr create \
      #     --base ${{ env.ENV_DESTINATION_BRANCH }} \
      #     --head ${{ env.ENV_SOURCE_BRANCH }} \
      #     --title '${{ env.ENV_PR_TITLE }}' \
      #     --body '${{ env.ENV_PR_BODY }}' \
      #     --reviewer ${{ env.ENV_REVIEWER }} \
      #     --assignee ${{ env.ENV_ASSIGNEE }} \
      #     --label ${{ env.ENV_LABEL }}
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}