name: Playground - Cron Schedule Workflow Action

on:
    schedule:
        - cron: "15 6 * * *" 
        - cron: "17 6 * * *" 
        - cron: "20 6 * * *" 
        - cron: "22 6 * * *" 

permissions:
  contents: write
  statuses: read
  actions: read

jobs:
  build:
    name: Cron Schedule Playground CI/CD
    runs-on: ubuntu-latest
    
    steps:
        - name: 'Checkout Code' 
          uses: actions/checkout@v3