env:

# Choose the ID for Pull Request Reviewer / Issue Assignee
  OWNER: ${{ vars.ID_ATHEESH }}

  # Choose any label from the below options. If you are choosing more than one label, make sure no space is provided.
  LABEL: ${{ vars.LABEL_BUG }}
  # ${{ vars.LABEL_BUG }},${{ vars.LABEL_ENHANCEMENTS }},${{ vars.LABEL_DOCUMENTATION }}

  # bug,documentation,duplicate,enhancement,"good first issue","help wanted",invalid,question,wontfix

# ******************************************** DO NOT ALTER ANY CODE BELOW ********************************************

name: Development Actions
  
on:
  push:
    tags:
      - 'PR-*'
      - 'ISSUE-*'

  pull_request_review:
      types: [submitted]

jobs:
  dev-jobs:
    name: PR / Issues
    runs-on: ${{ vars.LINUX_OS }}
    permissions: write-all

    env:
      ACTION_TYPE: ''
      SOURCE_BRANCH: ''
      FLUTTER_HOME: ''

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@master
        with:
          fetch-depth: 0  # Needed for some analyses

      - name: MS Teams Notification - Flutter Team
        if: always()
        uses: freenet-actions/ms-teams-deploy-card@master
        id: ms_teams_ostrum
        with:
            github-token: ${{ github.token }}
            webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
            show-on-start: false
            card-layout-exit: complete
            enable-review-diffs-action: false
            include-files: false
            custom-facts: |
              - name: While Merging PR
                value: "https://www.ostrumtech.com/"
            custom-actions: |
              - text: While Merging PR
                url: "https://www.ostrumtech.com/privacy-policy/"

      - name: Flutter Setup with Version ${{ vars.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
            channel: "stable"
            flutter-version: ${{ vars.FLUTTER_VERSION }}
            cache: true

      - name: Flutter Clean & Get Packages
        run: |
          flutter clean
          flutter pub get

      - name: Flutter Analyze (Static Code Analysis)
        run: flutter analyze

      - name: Flutter Unit Tests with Coverage
        run: flutter test --coverage

      - name: Trivy scan for Code Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: '.' # adjust path to your Flutter project
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL,LOW,MEDIUM,UNKNOWN
          output: trivy-report.txt  # or json, sarif, etc.

      - name: Trivy Scan Report
        run: cat trivy-report.txt

      - name: Extract Tag details
        if: github.ref_type == 'tag'
        run: echo "ACTION_TYPE=$(echo ${{ github.ref_name }} | cut -d- -f1)" >> $GITHUB_ENV

      - name: Check PR Review Approved
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'APPROVED'
        run: echo "ACTION_TYPE=PR_MERGE" >> $GITHUB_ENV

      - name: Get Source Branch
        if: ${{ env.ACTION_TYPE == 'PR' }}
        run: |
            branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
            echo "SOURCE_BRANCH=$branch" >> $GITHUB_ENV

      - name: Cache Flutter SDK
        if: ${{ env.ACTION_TYPE == 'PR' }}
        uses: actions/cache@master
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Create Pull Request 
        if: ${{ env.ACTION_TYPE == 'PR' }}
        run: |
            gh pr create \
            --base ${{ vars.PR_DESTINATION_BRANCH }} \
            --head ${{ env.SOURCE_BRANCH }} \
            --title '[AUTO] Tag - ${{ github.ref_name }}' \
            --body 'Auto created by @${{ github.event.sender.login }}: ${{ github.event.head_commit.message }}' \
            --reviewer ${{ env.OWNER }} \
            --assignee ${{ github.event.sender.login }} \
            --label ${{ env.LABEL }}
        env:
            GITHUB_TOKEN: ${{ github.token }}
    
      - name: Auto-Merge Pull Request on Approval
        if: ${{ env.ACTION_TYPE == 'PR_MERGE' }}
        run: gh pr merge --merge --auto "${{ github.event.pull_request.number }}"
        env:
            GH_TOKEN: ${{ github.token }}

      - name: Create an Issue
        if: ${{ env.ACTION_TYPE == 'ISSUE' }}
        uses: actions-ecosystem/action-create-issue@v1
        with:
            github_token: ${{ github.token }}
            title: '[AUTO] Tag - ${{ github.ref_name }}'
            body: 'Auto created by @${{ github.event.sender.login }}: ${{ github.event.head_commit.message }}'
            labels: ${{ env.LABEL }}
            assignees: ${{ env.OWNER }}
