name: Playground - Merge PR Workflow Action

on:
    pull_request_review:
        types: [submitted]

permissions:
  contents: write

env:
  ENV_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
    approved:
        name: Merge PR Playground CI/CD
        if: github.event.review.state == 'APPROVED'
        runs-on: ubuntu-latest

        steps:
        - name: PR Approved Logs
          run: |
            echo "This PR was approved"
            echo "ref=${{ env.ENV_PR_NUMBER }}"

        - name: Auto Merge on Review
          run: |
            gh pr merge --pull-request ${{ env.ENV_PR_NUMBER }}
