name: Playground - Merge PR Workflow Action

on:
    pull_request_review:
        types: [submitted]

permissions:
  contents: write

jobs:
    approved:
        name: Merge PR Playground CI/CD
        if: github.event.review.state == 'APPROVED'
        runs-on: ubuntu-latest

        steps:
        - name: PR Approved Log
          run: echo "This PR was approved"
