name: Playground - Merge PR Workflow Action

on:
    pull_request_review:
        types: [submitted]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

env:
  ENV_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
    approved:
        name: Merge PR Playground CI/CD
        if: github.event.review.state == 'APPROVED'
        runs-on: ubuntu-latest

        steps:
        - name: PR Approved Logs
          run: |
            echo "This PR was approved"
            echo "Head:=${{ github.event.pull_request.head }}"
            echo "Base:=${{ github.event.pull_request.base }}"
            echo "Title:=${{ github.event.pull_request.title }}"
            echo "Body:=${{ github.event.pull_request.body }}"
            echo "Labels:=${{ github.event.pull_request.labels }}"
            echo "URL:=${{ github.event.pull_request.url }}"

        - name: Auto Merge on Review
          run: |
            gh pr merge --admin # ${{ env.ENV_PR_NUMBER }}
          env:
            GH_TOKEN: ${{ github.token }}
