name: Playground - Merge PR Workflow Action

on:
    pull_request_review:
        types: [submitted]

permissions:
  contents: write

jobs:
    merge-pr:
      name: Merge PR Playground CI/CD
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Get PR Details
          run: |
            PULL_REQUEST_NUMBER=$GITHUB_EVENT_NUMBER
            PULL_REQUEST_URL=https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PULL_REQUEST_NUMBER}
            PULL_REQUEST_DATA=$(curl -s -X GET ${PULL_REQUEST_URL} -H "Authorization: Bearer ${GITHUB_TOKEN}")
            APPROVED_REVIEWS=$(jq -r '.reviews[] | select(.state == "APPROVED") | .user.login' <<< "${PULL_REQUEST_DATA}")
          