name: OWASP Dependency Check

on:
  push:


jobs:
    tests:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2

          - name: Flutter Setup
            uses: subosito/flutter-action@v2
            with:
                channel: "stable"
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                cache: true
                
          - name: Restore packages
            run: flutter pub get
            
          - name: Analyze
            run: flutter analyze

          - name: Run tests
            run: flutter test --coverage