name: OWASP Dependency Check

on:
  push:


jobs:
    tests:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2

          - name: Flutter Setup
            uses: subosito/flutter-action@v2
            with:
                channel: "stable"
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                cache: true

          - name: Restore packages
            run: flutter pub get
            
          - name: Analyze
            run: flutter analyze

          - name: Run tests
            run: flutter test --coverage

          - name: Upload coverage to codecov
            run: curl -s https://codecov.io/bash
            shell: bash

          - name: MS Teams Notification
            if: always()
            uses: freenet-actions/ms-teams-deploy-card@master
            id: ms_teams_ostrum
            with:
                github-token: ${{ github.token }}
                webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
                show-on-start: false
                card-layout-exit: complete
                enable-review-diffs-action: false
                include-files: false
