name: Pull Request Actions

on:
  push: # To create PR on tag creation
    tags:
    - 'PR-*'

  pull_request: # If PR is created to the below branches
    branches: [ main ]

  pull_request_review: # If any PR review is submitted
      types: [submitted]

jobs:
  CreatePullRequest:
    name: Create Pull Request
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions: write-all
    
    env:
      ENV_DESTINATION_BRANCH: main
      ENV_SOURCE_BRANCH: DEV # Below target branch must be setup in secrets
      ENV_PR_TITLE: Auto create ${{ github.ref_name }}
      ENV_PR_BODY: Created by ${{ github.event.sender.login }}
      ENV_REVIEWER: Atheesh-Alva
      ENV_ASSIGNEE: ${{ github.event.sender.login }}
      ENV_LABEL: bug

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Create Pull Request 
        run: |
          gh pr create \
          --base ${{ env.ENV_DESTINATION_BRANCH }} \
          --head ${{ env.ENV_SOURCE_BRANCH }} \
          --title '${{ env.ENV_PR_TITLE }}' \
          --body '${{ env.ENV_PR_BODY }}' \
          --reviewer ${{ env.ENV_REVIEWER }} \
          --assignee ${{ env.ENV_ASSIGNEE }} \
          --label ${{ env.ENV_LABEL }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  PullRequestAlert:
    name: Pull Request Alert
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: PR Logs
        run: |
          echo "url:${{ github.event.pull_request.url }}"

      - name: MS Teams Notification
        uses: freenet-actions/ms-teams-deploy-card@master
        id: ms_teams_ostrum
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
          show-on-start: false
          card-layout-exit: complete
          enable-review-diffs-action: false
          include-files: false
          custom-facts: |
            - name: View Ostrum Tech website
              value: "https://www.ostrumtech.com/"
          custom-actions: |
            - text: Check Privacy Policy
              url: "https://www.ostrumtech.com/privacy-policy/"
   
  PullRequestAutoMerge:
    name: Pull Request Auto Merge
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'
    
    steps:
      - name: PR Logs
        run: |
          echo "event_name:${{ github.event_name }}"
                            
        
# github.event_name = pull_request_review / pull_request
# github.ref_type = tag

# name: PR Merge

# on:
#   pull_request_review:
#       types: [submitted]

# permissions:
#   contents: write
#   pull-requests: write
#   repository-projects: write

# env:
#   ENV_PR_NUMBER: ${{ github.event.pull_request.number }}

# jobs:
#     approved:
#         name: Merge PR Playground CI/CD
#         if: github.event.review.state == 'APPROVED'
#         runs-on: ubuntu-latest
#         permissions: write-all

#         steps:
#           - name: Checkout Code
#             uses: actions/checkout@v3
            
#           - name: PR Approved Logs
#             run: |
#               echo "This PR was approved"
#               echo "Head:${{ github.event.pull_request.head.ref }}"
#               echo "Base:${{ github.event.pull_request.base.label }}"
#               echo "Title:${{ github.event.pull_request.title }}"
#               echo "Body:${{ github.event.pull_request.body }}"
#               echo "Labels:${{ github.event.pull_request.labels.name }}"
#               echo "URL:${{ github.event.pull_request.url }}"

#           - name: Enable Pull Request Auto-merge
#             run: gh pr merge --merge --auto "${{ env.ENV_PR_NUMBER }}"
#             env:
#               GH_TOKEN: ${{ github.token }}


# name: Create PR

# on:
#   push:
#     tags:
#     - 'PR-*'

# env:
#   ENV_SOURCE_BRANCH: DEV
#   # Below target branch must be setup in secrets
#   ENV_DESTINATION_BRANCH: main
#   ENV_PR_TITLE: Auto create ${{ github.ref_name }}
#   ENV_PR_BODY: Created by ${{ github.event.sender.login }}
#   ENV_REVIEWER: Atheesh-Alva
#   ENV_ASSIGNEE: ${{ github.event.sender.login }}
#   ENV_LABEL: bug

# jobs:
#   build:
#     name: Create PR
#     runs-on: ubuntu-latest
#     permissions: write-all
    
#     steps: