name: PR Alert

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  statuses: read
  actions: read

jobs:
  Alert:
    name: Pull Request Alert
    runs-on: ubuntu-latest
    
    steps:
      - name: 'MS Teams Notification' 
        uses: freenet-actions/ms-teams-deploy-card@master
        id: ms_teams_ostrum
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
          show-on-start: false
          card-layout-exit: complete
          enable-review-diffs-action: false
          include-files: false
          custom-facts: |
            - name: Alert Type
              value: "Pull Request to main branch"