name: Pull Request Actions

on:
  push: # To create PR on tag creation
    tags:
    - 'PR-*'

  pull_request: # If PR is created to the below branches
    branches: [ main ]

  pull_request_review: # If any PR review is submitted
      types: [submitted]

jobs:
  Logs:
    name: Logs
    runs-on: ubuntu-latest
    
    steps:
      - name: PR Logs
        run: |
          echo "action:${{ github.action }}"
          echo "action_ref:${{ github.action_ref }}"
          echo "action_status:${{ github.action_status }}"
          echo "event_name:${{ github.event_name }}"
          echo "ref:${{ github.ref }}"
          echo "ref_name:${{ github.ref_name }}"
          echo "ref_type:${{ github.ref_type }}"

  CreatePullRequest:
    name: Create Pull Request
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    
    steps:
      - name: PR Logs
        run: |
          echo "ref_name:${{ github.ref_name }}"
          echo "ref_type:${{ github.ref_type }}"

  PullRequestAlert:
    name: Pull Request Alert
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: PR Logs
        run: |
          echo "event_name:${{ github.event_name }}"
   
  PullRequestAutoMerge:
    name: Pull Request Auto Merge
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'
    
    steps:
      - name: PR Logs
        run: |
          echo "event_name:${{ github.event_name }}"
                            
        
# github.event_name = pull_request_review / pull_request
# github.ref_type = tag

# name: PR Merge

# on:
#   pull_request_review:
#       types: [submitted]

# permissions:
#   contents: write
#   pull-requests: write
#   repository-projects: write

# env:
#   ENV_PR_NUMBER: ${{ github.event.pull_request.number }}

# jobs:
#     approved:
#         name: Merge PR Playground CI/CD
#         if: github.event.review.state == 'APPROVED'
#         runs-on: ubuntu-latest
#         permissions: write-all

#         steps:
#           - name: Checkout Code
#             uses: actions/checkout@v3
            
#           - name: PR Approved Logs
#             run: |
#               echo "This PR was approved"
#               echo "Head:${{ github.event.pull_request.head.ref }}"
#               echo "Base:${{ github.event.pull_request.base.label }}"
#               echo "Title:${{ github.event.pull_request.title }}"
#               echo "Body:${{ github.event.pull_request.body }}"
#               echo "Labels:${{ github.event.pull_request.labels.name }}"
#               echo "URL:${{ github.event.pull_request.url }}"

#           - name: Enable Pull Request Auto-merge
#             run: gh pr merge --merge --auto "${{ env.ENV_PR_NUMBER }}"
#             env:
#               GH_TOKEN: ${{ github.token }}


# name: Create PR

# on:
#   push:
#     tags:
#     - 'PR-*'

# env:
#   ENV_SOURCE_BRANCH: DEV
#   # Below target branch must be setup in secrets
#   ENV_DESTINATION_BRANCH: main
#   ENV_PR_TITLE: Auto create ${{ github.ref_name }}
#   ENV_PR_BODY: Created by ${{ github.event.sender.login }}
#   ENV_REVIEWER: Atheesh-Alva
#   ENV_ASSIGNEE: ${{ github.event.sender.login }}
#   ENV_LABEL: bug

# jobs:
#   build:
#     name: Create PR
#     runs-on: ubuntu-latest
#     permissions: write-all
    
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3
        
#       - name: Logs
#         run: |
#           echo "default_branch:${{ github.event.repository.default_branch }}"
#           echo "master_branch:${{ github.event.repository.master_branch }}"
          
#           echo "name:${{ github.event.pusher.name }}"
#           echo "username:${{ github.event.head_commit.author.username }}"
#           echo "name:${{ github.event.head_commit.author.name }}"
#           echo "username:${{ github.event.head_commit.committer.username }}"
#           echo "name:${{ github.event.head_commit.committer.name }}"

#       - name: Create PR
#         run: |
#           gh pr create \
#           --base ${{ env.ENV_DESTINATION_BRANCH }} \
#           --head ${{ env.ENV_SOURCE_BRANCH }} \
#           --title '${{ env.ENV_PR_TITLE }}' \
#           --body '${{ env.ENV_PR_BODY }}' \
#           --reviewer ${{ env.ENV_REVIEWER }} \
#           --assignee ${{ env.ENV_ASSIGNEE }} \
#           --label ${{ env.ENV_LABEL }}
#         env:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}