name: Pull Request Actions

on:
  push: # To create PR on tag creation
    tags:
    - 'PR-*'

  # pull_request: # If PR is created to the below branches
  #   branches: [ main ]

  pull_request_review: # If any PR review is submitted
      types: [submitted]

jobs:
  CreatePullRequest:
    name: Create Pull Request
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions: write-all
    
    env:
      DESTINATION_BRANCH: main
      SOURCE_BRANCH: # DO NOT CHANGE
      PR_TITLE: Auto create ${{ github.ref_name }}
      PR_BODY: Created by ${{ github.event.sender.login }}
      REVIEWER: Atheesh-Alva
      ASSIGNEE: ${{ github.event.sender.login }}
      LABEL: bug
      FLUTTER_VERSION: "3.22.0"
      FLUTTER_HOME: 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Get Source Branch
        run: |
          branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
          echo "SOURCE_BRANCH=$branch" >> $GITHUB_ENV

      - name: MS Teams Notification - Flutter Team
        if: always()
        uses: freenet-actions/ms-teams-deploy-card@master
        id: ms_teams_ostrum
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
          show-on-start: false
          card-layout-exit: complete
          enable-review-diffs-action: false
          include-files: false
          custom-facts: |
            - name: View Ostrum Tech website
              value: "https://www.ostrumtech.com/"
          custom-actions: |
            - text: Check Privacy Policy
              url: "https://www.ostrumtech.com/privacy-policy/"

      # - name: Flutter Setup
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: "stable"
      #     flutter-version: ${{ env.FLUTTER_VERSION }}
      #     cache: true

      # - name: Flutter Clean
      #   run: flutter clean

      # - name: Flutter Pub Get
      #   run: flutter pub get
    
      # - name: 'Cache pub dependencies'
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ env.FLUTTER_HOME }}/.pub-cache
      #     key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
      #     restore-keys: ${{ runner.os }}-pub-
  
      - name: Create Pull Request 
        run: |
          gh pr create \
          --base ${{ env.DESTINATION_BRANCH }} \
          --head ${{ env.SOURCE_BRANCH }} \
          --title '${{ env.PR_TITLE }}' \
          --body '${{ env.PR_BODY }}' \
          --reviewer ${{ env.REVIEWER }} \
          --assignee ${{ env.ASSIGNEE }} \
          --label ${{ env.LABEL }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
  PullRequestAutoMerge:
    name: Pull Request Auto Merge
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Auto-merge Pull Request on Approval
        run: gh pr merge --merge --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: MS Teams Notification - Flutter Team
        if: always()
        uses: freenet-actions/ms-teams-deploy-card@master
        id: ms_teams_ostrum
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
          show-on-start: false
          card-layout-exit: complete
          enable-review-diffs-action: false
          include-files: false
          custom-facts: |
            - name: View Ostrum Tech website
              value: "https://www.ostrumtech.com/"
          custom-actions: |
            - text: Check Privacy Policy
              url: "https://www.ostrumtech.com/privacy-policy/"
    