name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'
 
jobs:
  logs:
    name: Logs
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      BUG: true
      ENHANCEMENT: true
      HELP: true
      INVALID: true
      QUESTION: true
      DUPLICATE: true
      DOCUMENTATION: false
      LABEL:
  
    steps:
      - name: Check
        run: |
          if [${{ env.BUG }}]
          then
            echo "LABEL=${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
          fi
          echo "LABEL=${{ env.LABEL }}"

      - name: Logs
        run: |
          echo "LABEL=${{ env.LABEL }}"
