name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  logs:
    name: Actions
    runs-on: ${{ vars.LINUX_OS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Actions
        run: sed -i '' 's|.*|${{ vars.DEBUG_JSON }}|' assets/raw/js.json

      - name: Read user_data.json
        id: user_data
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/raw_json/user_data.json

      - name: Echo user_data.json
        run: echo "${{ steps.user_data.outputs.content }}"