name: Playground - Standard Workflow Action

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  build:
    name: Standard Playground CI/CD
    runs-on: macos-14
    
    steps:
    - name: 'Checkout Code' 
      uses: actions/checkout@v3

