name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  logs:
    name: Actions
    runs-on: ${{ vars.MAC_OS }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-2'
      AWS_API_ID: ${{ secrets.AWS_APPSYNC_API_ID }}

    steps:
      - name: Convert file to base64
        run: |
          echo '{"name":"jsdaniell", "password":"mypass"}' >> test_json.json
          cat test_json.json
          base64 test_json.json > test_json.base64
          cat test_json.base64
        # base64 -i test_json.json -o test_json.base64 FOR MACOS


      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Fetch AWS AppSync Schema
      #   run: |
      #     npm install -g aws-appsync
      #     aws appsync get-introspection-schema --api-id $AWS_API_ID --format SDL --region $AWS_REGION --no-include-directives schema.json