name: Example Workflow

on:
  push:
    branches:
      - main

jobs:

  job1:
    runs-on: ubuntu-latest
    
    outputs:
      RELEASE_DATE: ${{ steps.set-release-date.outputs.RELEASE_DATE }}
      
    steps:
    - name: Set RELEASE_DATE
      id: set-release-date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> $GITHUB_OUTPUT
        
  job2:
    needs: job1
    runs-on: ubuntu-latest
    
    steps:
    - name: Get RELEASE_DATE
      run: |
        echo "RELEASE_DATE from job1: ${{ needs.job1.outputs.RELEASE_DATE }}"
        
  job3:
    needs: job1
    runs-on: ubuntu-latest
    
    steps:
    - name: Get RELEASE_DATE
      run: |
        echo "RELEASE_DATE from job1: ${{ needs.job1.outputs.RELEASE_DATE }}"
