name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'
 
env:
  BUG: true
  ENHANCEMENT: true
  HELP: true
  INVALID: true
  QUESTION: true
  DUPLICATE: true
  DOCUMENTATION: false
  LABEL:
  
jobs:
  logs:
    name: Logs
    runs-on: ubuntu-latest
    steps:
      - name: Logs
        run: |
          echo "FLUTTER_VERSION=${{ vars.FLUTTER_VERSION }}"
          echo "ID_ATHEESH=${{ vars.ID_ATHEESH }}"
          echo "LABEL=${{ env.BUG == true && vars.LABEL_BUG || env.BUG }}" >> $GITHUB_ENV
          echo "LABEL=${{ env.LABEL }}"
