name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  logs:
    name: Actions
    runs-on: ${{ vars.LINUX_OS }}

    steps:
      - name: Create file
        run: |
          printf "Hello\nWorld\n" > hw.txt
          echo First > other.txt
          echo Second Line >> other.txt
          echo Third >> other.txt
          
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Edit file
      #   run: |
      #     sed -i 's|.*|${{ vars.ID_ATHEESH }}|' assets/raw/encoded.base64
      #   # sed -i '' 's|.*|${{ vars.DEBUG_JSON }}|' assets/raw/encoded.base64

      # - name: Read encoded.base64
      #   id: encoded
      #   uses: juliangruber/read-file-action@v1
      #   with:
      #     path: assets/raw/encoded.base64

      # - name: Echo encoded.base64
      #   run: |
      #     echo "${{ steps.encoded.outputs.content }}"

      # - name: Setup JAVA for Android
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: "zulu"
      #     java-version: ${{ vars.JAVA_VERSION }}
      #     cache: "gradle"

      # - name: Flutter Setup
      #   uses: subosito/flutter-action@v2
      #   with:
      #       channel: "stable"
      #       flutter-version: ${{ vars.FLUTTER_VERSION }}
      #       cache: true

      # - name: Build APK File
      #   run: |
      #     flutter build apk \
      #       --target=lib/main.dart \
      #       --release

      # - name: Upload APK to GitHub Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: 'APK_JSON'
      #     path: build/app/outputs/flutter-apk/app-release.apk
            