name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'
 
env:
  BUG: true
  ENHANCEMENT: true
  HELP: true
  INVALID: true
  QUESTION: true
  DUPLICATE: true
  DOCUMENTATION: false
  LABEL:
  
jobs:
  logs:
    name: Logs
    runs-on: ubuntu-latest
    steps:
      - name: Logs
        run: |
          if [${{ env.BUG }}]
          then
            echo "LABEL=${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
          fi
          echo "LABEL=${{ env.LABEL }}"
