name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  logs:
    name: Actions
    runs-on: ${{ vars.LINUX_OS }}
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: pip install awscli

      - name: Fetch AppSync Schema
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_API_ID: ${{ secrets.AWS_APPSYNC_API_ID }}
        run: |
          aws appsync get-introspection-schema --api-id $AWS_API_ID --format SDL --no-include-directives outfile=schema.graphql
        # aws appsync get-introspection-schema --api-id $AWS_API_ID --format SDL --region $AWS_REGION --output schema.graphql --debug

      # - name: Get AppSync schema
      #   run: aws appsync get-schema --api-id ${{ secrets.AWS_APPSYNC_API_ID }} --output text --debug > schema.graphql