name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  logs:
    name: Actions
    runs-on: ${{ vars.LINUX_OS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Actions
        run: |
          sed -i "s/.*/${{ vars.DEBUG_JSON }}/" assets/raw/js.json
        # sed -i 's|.*|'"${{ vars.DEBUG_JSON }}"'|' assets/raw/js.json
        # sed -i '' 's|cognitoBase64 = \x27\x27|cognitoBase64 = \x27${{ secrets.ES_COGNITO_CREDENTIALS_JSON_BASE64 }}\x27|' lib/app/app_credentials.dart

      - name: Read js.json
        id: js
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/raw/js.json

      - name: Echo js.json
        run: |
          output=$({{ steps.js.outputs.content }})
          echo -n "$output