name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  logs:
    name: Actions
    runs-on: ${{ vars.LINUX_OS }}

    env:
      AWS_ACCESS_KEY_ID: 'https://nalw7rwuybdp5juqqq5m3t26rm.appsync-api.eu-west-2.amazonaws.com/graphql'
      AWS_SECRET_ACCESS_KEY: 'da2-cfoextlqxbbxhiyqfqmyza57fa'
      AWS_REGION: 'eu-west-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: pip install awscli

      - name: Get AppSync schema
        run: aws appsync get-schema --api-id 5bf7gyppzzczna7vog65dthndi --output text > schema.graphql