name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'
 
jobs:
  logs:
    name: Logs
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      BUG: true
      ENHANCEMENT: true
      DOCUMENTATION: false
      LABEL:
  
    steps:
      - name: Check
        run: |

          if [ ${{ env.BUG }} ]; then
            echo "LABEL=${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
            if [ ${{ env.ENHANCEMENT }} ]; then
              echo "LABEL=${{ env.LABEL }},${{ vars.LABEL_ENHANCEMENT }}" >> $GITHUB_ENV
            elif [ ${{ env.DOCUMENTATION }} ]; then
              echo "LABEL=${{ env.LABEL }},${{ vars.LABEL_DOCUMENTATION }}" >> $GITHUB_ENV
            else
              echo "${{ env.LABEL }}"
            fi
          elif [ ${{ env.ENHANCEMENT }} ]; then
            echo "LABEL=${{ vars.LABEL_ENHANCEMENT }}" >> $GITHUB_ENV
          elif [ ${{ env.DOCUMENTATION }} ]; then
            echo "LABEL=${{ vars.LABEL_DOCUMENTATION }}" >> $GITHUB_ENV
          else
            echo "${{ env.LABEL }}"
          fi



          # if [ -z ${{ env.LABEL }} ]; then
          #   echo "EMPTY"
          #   echo "LABEL=${{ vars.LABEL_BUG }},${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
          # else
          #   echo "NOT EMPTY"
          # fi

      - name: Logs
        run: |
          echo "LABEL=${{ env.LABEL }}"
