name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

    # APK-85-1.7.12

  # - "R+[0-9]+[0-9]+[0-9]+[0-9]+-[0-9]+.[0-9]+.[0-9]+-V+[0-9]+[0-9]"

    - 'APK-B*-V*'
 
jobs:
  logs:
    name: Logs
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      BUG: true
      ENHANCEMENT: true
      DOCUMENTATION: false
      LABEL:
      ACTION_TYPE:
      VERSION:
      BUILD_NUMBER:
  
    steps:
      - name: Actions
        run: |
          echo "ACTION_TYPE=$(echo ${{ github.ref_name }} | cut -d- -f1)" >> $GITHUB_ENV
          echo "VERSION=$(echo ${{ github.ref_name }} | cut -d- -f2)" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$(echo ${{ github.ref_name }} | cut -d- -f3)" >> $GITHUB_ENV

      - name: Logs
        run: |
          echo "ref_name=${{ github.ref_name }}"
          echo "ACTION_TYPE=${{ env.ACTION_TYPE }}"
          echo "VERSION=${{ env.VERSION }}"
          echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}"
          value="${{ github.ref_name }}"
          substring="${value:1}"
          echo "Substring: $substring"



      # - name: Check
      #   run: |

      #     if [ ${{ env.BUG }} ]; then
      #       echo "LABEL=${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
      #       if [ ${{ env.ENHANCEMENT }} ]; then
      #         echo "LABEL=${{ env.LABEL }},${{ vars.LABEL_ENHANCEMENT }}" >> $GITHUB_ENV
      #       elif [ ${{ env.DOCUMENTATION }} ]; then
      #         echo "LABEL=${{ env.LABEL }},${{ vars.LABEL_DOCUMENTATION }}" >> $GITHUB_ENV
      #       else
      #         echo "${{ env.LABEL }}"
      #       fi
      #     elif [ ${{ env.ENHANCEMENT }} ]; then
      #       echo "LABEL=${{ vars.LABEL_ENHANCEMENT }}" >> $GITHUB_ENV
      #     elif [ ${{ env.DOCUMENTATION }} ]; then
      #       echo "LABEL=${{ vars.LABEL_DOCUMENTATION }}" >> $GITHUB_ENV
      #     else
      #       echo "${{ env.LABEL }}"
      #     fi



          # if [ -z ${{ env.LABEL }} ]; then
          #   echo "EMPTY"
          #   echo "LABEL=${{ vars.LABEL_BUG }},${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
          # else
          #   echo "NOT EMPTY"
          # fi

