name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'
 
jobs:
  # Checkout:
  #   name: Checking out code
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: 'Checkout Code' 
  #       uses: actions/checkout@v3

  Logs:
    name: Logs
    runs-on: ubuntu-latest
    # needs: Checkout

    env:
      SOURCE_BRANCH:
         
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Get Branch
        run: |
          branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
          echo "SOURCE_BRANCH=$branch" >> $GITHUB_ENV

      - name: Print Branch
        run: |
          echo ${{ env.SOURCE_BRANCH }}