name: Playground - Standard Workflow Action

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  build:
    name: Standard Playground CI/CD
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout Code' 
      uses: actions/checkout@v3

    - name: Super-Linter Run
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ github.token }}