# name: Standard

# on:
#   push:
#     tags:
#     - 'Run-+[0-9]+[0-9]+[0-9]'
 
# jobs:
#   # Checkout:
#   #   name: Checking out code
#   #   runs-on: ubuntu-latest
    
#   #   steps:
#   #     - name: 'Checkout Code' 
#   #       uses: actions/checkout@v3

#   Logs:
#     name: Logs
#     runs-on: ubuntu-latest
#     # needs: Checkout

#     env:
#       SOURCE_BRANCH:
         
#     steps: 
#       - name: Checkout source code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
        
#       - name: Get Branch
#         run: |
#           branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
#           echo "SOURCE_BRANCH=$branch" >> $GITHUB_ENV

#       - name: Print Branch
#         run: |
#           echo ${{ env.SOURCE_BRANCH }}

name: Example Workflow

on:
  push:
    branches:
      - DEV

jobs:

  job1:
    runs-on: ubuntu-latest
    
    outputs:
      RELEASE_DATE: ${{ steps.set-release-date.outputs.RELEASE_DATE }}
      
    steps:
    - name: Set RELEASE_DATE
      id: set-release-date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> $GITHUB_OUTPUT
        
  job2:
    needs: job1
    runs-on: ubuntu-latest
    
    steps:
    - name: Get RELEASE_DATE
      run: |
        echo "RELEASE_DATE from job1: ${{ needs.job1.outputs.RELEASE_DATE }}"
        
  job3:
    needs: job1
    runs-on: ubuntu-latest
    
    steps:
    - name: Get RELEASE_DATE
      run: |
        echo "RELEASE_DATE from job1: ${{ needs.job1.outputs.RELEASE_DATE }}"
