name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  logs:
    name: Actions
    runs-on: ${{ vars.LINUX_OS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Actions
        run: |
          DEBUG_JSON=${{ vars.DEBUG_JSON }}
          sed -i "s/.*/${DEBUG_JSON}/" assets/raw/js.json
        # sed -i 's|.*|'"${{ vars.DEBUG_JSON }}"'|' assets/raw/js.json
        # sed -i '' 's|cognitoBase64 = \x27\x27|cognitoBase64 = \x27${{ secrets.ES_COGNITO_CREDENTIALS_JSON_BASE64 }}\x27|' lib/app/app_credentials.dart

      - name: Read js.json
        id: js
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/raw/js.json

      - name: Echo js.json
        run: |
          output=${{ steps.js.outputs.content }}
          echo -n "$output

      # - name: Setup JAVA for Android
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: "zulu"
      #     java-version: ${{ vars.JAVA_VERSION }}
      #     cache: "gradle"

      # - name: Flutter Setup
      #   uses: subosito/flutter-action@v2
      #   with:
      #       channel: "stable"
      #       flutter-version: ${{ vars.FLUTTER_VERSION }}
      #       cache: true

      # - name: Build APK File
      #   run: |
      #     flutter build apk \
      #       --target=lib/main.dart \
      #       --release

      # - name: Upload APK to GitHub Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: 'APK_JSON'
      #     path: build/app/outputs/flutter-apk/app-release.apk
            