name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  job1:
    name: Actions
    runs-on: ${{ vars.LINUX_OS }}

    outputs:
      LABEL: ${{ steps.read-json.outputs.LABEL }}

    env:
      AWS_REGION: 'eu-west-2'
      AWS_API_ID: ${{ secrets.AWS_APPSYNC_API_ID }}

    steps:
    - name: Extract Workflow JSON details
      id: read-json
      run: |
        echo "${{ vars.WORKFLOW_JSON }}" > lib/workflow.json

        # Use jq to parse and filter keys with true values
        LABEL=$(jq -r '.commit_details | to_entries | map(select(.value == true) | .key) | join(",")' lib/workflow.json)

        echo "LABEL=$LABEL" >> $GITHUB_OUTPUT


  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use LABEL output
        run: echo "Labels are ${{ needs.job1.outputs.LABEL }}"
