name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

    # R24-0503/B21/V1.7.12 - APK, AAB, IPA, Play Store - Internal, TestFlight
    - 'R*/B*/V*'
    # AND/B21/V1.7.12 - APK, AAB, Play Store - Internal
    - 'AND/B*/V*'
    # GPS/B21/V1.7.12 - AAB, Play Store - Internal
    - 'GPS/B*/V*'
    # IOS/B21/V1.7.12 - IPA, TestFlight
    - 'IOS/B*/V*'
    # APK/B21/V1.7.12 - APK
    - 'APK/B*/V*'
    # AAB/B21/V1.7.12 - AAB
    - 'AAB/B*/V*'
    # IPA/B21/V1.7.12 - IPA
    - 'IPA/B*/V*'
 
jobs:
  logs:
    name: Logs
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      BUG: true
      ENHANCEMENT: true
      DOCUMENTATION: false
      LABEL:
      ACTION_TYPE:
      APP_VERSION:
      BUILD_NUMBER:
  
    steps:
      - name: Actions
        run: |
          echo "ACTION_TYPE=$(echo ${{ github.ref_name }} | cut -d '/' -f 1)" >> $GITHUB_ENV
          build_number=$(echo ${{ github.ref_name }} | cut -d '/' -f 2)
          echo "BUILD_NUMBER=${build_number:1}" >> $GITHUB_ENV
          app_version=$(echo ${{ github.ref_name }} | cut -d '/' -f 3)
          echo "APP_VERSION=${app_version:1}" >> $GITHUB_ENV

      - name: Logs
        run: |
          echo "ref_name=${{ github.ref_name }}"
          echo "ACTION_TYPE=${{ env.ACTION_TYPE }}"
          echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}"
          echo "APP_VERSION=${{ env.APP_VERSION }}"



      # - name: Check
      #   run: |

      #     if [ ${{ env.BUG }} ]; then
      #       echo "LABEL=${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
      #       if [ ${{ env.ENHANCEMENT }} ]; then
      #         echo "LABEL=${{ env.LABEL }},${{ vars.LABEL_ENHANCEMENT }}" >> $GITHUB_ENV
      #       elif [ ${{ env.DOCUMENTATION }} ]; then
      #         echo "LABEL=${{ env.LABEL }},${{ vars.LABEL_DOCUMENTATION }}" >> $GITHUB_ENV
      #       else
      #         echo "${{ env.LABEL }}"
      #       fi
      #     elif [ ${{ env.ENHANCEMENT }} ]; then
      #       echo "LABEL=${{ vars.LABEL_ENHANCEMENT }}" >> $GITHUB_ENV
      #     elif [ ${{ env.DOCUMENTATION }} ]; then
      #       echo "LABEL=${{ vars.LABEL_DOCUMENTATION }}" >> $GITHUB_ENV
      #     else
      #       echo "${{ env.LABEL }}"
      #     fi



          # if [ -z ${{ env.LABEL }} ]; then
          #   echo "EMPTY"
          #   echo "LABEL=${{ vars.LABEL_BUG }},${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
          # else
          #   echo "NOT EMPTY"
          # fi

