name: Playground - Standard Workflow Action

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  build:
    name: Standard Playground CI/CD
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Code' 
        uses: actions/checkout@v3

      - name: 'MS Teams Notification' 
        uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        id: ms_teams_ostrum
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_PLAYGROUND_WEBHOOK_URI }}
          show-on-start: false
          card-layout-exit: complete
          enable-review-diffs-action: false
          include-files: false
          custom-facts: |
            - name: View Ostrum Tech website
              value: "https://www.ostrumtech.com"
          custom-actions: |
            - text: View Ostrum Tech website
              url: "https://www.ostrumtech.com"

    # - name: Super-Linter Run
    #   uses: github/super-linter@v4
    #   env:
    #     DEFAULT_BRANCH: main
    #     GITHUB_TOKEN: ${{ github.token }}