name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.set-label.outputs.label }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read JSON and extract labels
        id: set-label
        run: |
          # echo "${{ vars.WORKFLOW_JSON }}" > lib/workflow.json
          
          # Read the JSON file
          json=$(cat lib/workflow.json)
          
          # Use jq to extract keys with true values from commit_details
          labels=$(echo "$json" | jq -r '.commit_details | to_entries | map(select(.value == true)) | map(.key) | join(",")')
          
          echo "LABEL=$labels"
          echo "::set-output name=label::$labels"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use LABEL from job1
        run: |
          echo "Labels from job1: ${{ needs.job1.outputs.label }}"
  