name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'
 
jobs:
  logs:
    name: Logs
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      BUG: true
      ENHANCEMENT: true
      HELP: true
      INVALID: true
      QUESTION: true
      DUPLICATE: true
      DOCUMENTATION: false
      LABEL:
  
    steps:
      - name: Check
        run: |
          if [ -z ${{ env.LABEL }} ]; then
            echo "EMPTY"
            echo "${{ vars.LABEL_BUG }} + ${{ vars.LABEL_ENHANCEMENT }}"
          else
            echo "NOT EMPTY"
          fi
  # if [ ${{ env.BUG }} ]; then
  #   echo "LABEL=${{ vars.LABEL_BUG }}" >> $GITHUB_ENV
  # else
  #   echo "LABEL=${{ vars.LABEL_DOCUMENTATION }}" >> $GITHUB_ENV
  # fi

      - name: Logs
        run: |
          echo "LABEL=${{ env.LABEL }}"
