name: Standard

on:
  push:
    tags:
    - 'Run-+[0-9]+[0-9]+[0-9]'

jobs:
  logs:
    name: Actions
    runs-on: ${{ vars.LINUX_OS }}

    steps:
      - name: Actions
        run: sed -i '' 's|.*|${{ vars.DEBUG_JSON }}|g' assets/raw_json/user_data.json
